#!/bin/sh
if [ -z "$1" ]; then
  echo "Usage: $0 /path/to/file/to/fix" >&2
  exit 1
fi
if [ "`head -1 $1`" != "#!/usr/bin/env ruby" ]; then
  exit 0
fi
cat <<EOS | ed -s $1  2>&1 >/dev/null
1c
#!/opt/csw/bin/ruby
ENV['PATH'] = '/opt/csw/bin:/usr/local/bin:/usr/bin:/bin' unless ENV['PATH'] and ENV['PATH'].include?('/opt/csw/bin')
.

w
q
EOS
